name: reading_habit_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_generative_ai: ^0.4.7
  http: ^1.2.0
  # ★ここを追加しました！
  audioplayers: ^5.2.1 
  fl_chart: ^0.70.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/video_project.mp4
    - assets/amenooto.mp3 # 先ほど amonooto と言っていましたが、ここが amenooto になっているのでコードも合わせますね